spring:
  application:
    name: config
  security:
    user:
      name: root
      password: root
  cloud:
    config:
      server:
        native:
          searchLocations: D:/myself/workspace/github/cloud/config-repo
    bus:
      refresh:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    username: jsnx
    password: 123456
    virtualHost: /
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8888
eureka:
  instance:
    ip-address: 127.0.0.1
    hostname: registry.spring.cloud
    prefer-ip-address: true
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.ip-address}:8761/eureka/
