spring:
  application:
    name: registry1
  security:
    user:
      name: root
      password: root

server:
  port: 8761

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.ip-address}:8762/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.ip-address}:8763/eureka/